-- database schema fix
-- tested and working

CREATE TABLE pallet (
    CODICE_PALLET INT(255) PRIMARY KEY,
    DIM_X_PALLET INT(255),
    DIM_Y_PALLET INT(255),
    DIM_Z_PALLET INT(255)
);

CREATE TABLE pacchi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ID_PACCO INT(255) NOT NULL UNIQUE,
    CODICE_PALLET INT(255),
    NUM_SPEDIZIONE INT(255),
    CODICE_CLIENTE INT(255),
    PESO_NETTO INT(255),
    PESO_LORDO INT(255),
    BASE_MAGGIORE INT(255),
    BASE_MINORE INT(255),
    ALTEZZA INT(255),
    FLAG_PALLETTIZZABILE VARCHAR,
    FLAG_SOVRAPPONIBILE VARCHAR,
    FLAG_RUOTABILE VARCHAR,
    FOREIGN KEY (CODICE_PALLET) REFERENCES pallet(CODICE_PALLET) ON DELETE SET NULL
);

-- inserting tests
INSERT INTO pallet (CODICE_PALLET, DIM_X_PALLET, DIM_Y_PALLET, DIM_Z_PALLET)
            VALUES (10, 1000, 500, 200),
                    (15, 600, 500, 200);

-- NB: non va specificato il codice pallet!
INSERT INTO pacchi (ID_PACCO, NUM_SPEDIZIONE, CODICE_CLIENTE, PESO_NETTO, PESO_LORDO, BASE_MAGGIORE, BASE_MINORE, ALTEZZA, FLAG_PALLETTIZZABILE, FLAG_SOVRAPPONIBILE, FLAG_RUOTABILE)
            VALUES  (1532, 1212, 454, 12, 55, 15, 82, 22, 'N', '', ''),
                    (5425, 1235, 444, 13, 54, 52, 65, 33, '', 'N', ''),
                    (5454, 4456, 666, 15, 54, 56, 23, 55, 'N', '', '');

-- re-link packs tests
UPDATE pacchi
SET CODICE_PALLET = 10
WHERE ID_PACCO IN (1532, 5425);
