-- SELEZIONE PACCHI A SISTEMA BY PALLET_ID

SELECT *
FROM `pacchi`
-- FILLARE NELLE PARENTESI LA LISTA DEGLI ID DEI PALLET PER CUI RECUPERARE I PACCHI, eg: (123, 3414, 15151)
WHERE pacchi.CODICE_PALLET IN (0)