-- UPDATE PACCHI
-- Query che registra tutti i pacchi per un singolo pallet.
-- Eseguire per un pallet alla volta.

-- VARIABILE_1: CODICE PALLET A CUI ASSEGNARE I PACCHI
SET @PALLET_ID = 125;

INSERT INTO pallet (CODICE_PALLET)
SELECT @PALLET_ID
WHERE NOT EXISTS (SELECT 1 FROM pallet WHERE CODICE_PALLET = @PALLET_ID);

UPDATE pacchi 
SET CODICE_PALLET = @PALLET_ID 
-- VARIABILE_2: CODICI DEI PACCHI DA ASSEGNARE AL PALLET
WHERE ID_PACCO IN (1, 2, 3);
